version: "3.7"
services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-dev
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: laravel
      SERVICE_NAME: mysql
    volumes:
#      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.0.2-apache
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
